export default {


    START_SET_USER:"START_SET_USER",
    SUCCESS_SET_USER:"SUCCESS_SET_USER",
    FAILURE_SET_USER:"FAILURE_SET_USER",


    START_REMOVE_USER:"SUCCESS_REMOVE_USER",
    REMOVED_USER:"REMOVED_USER",


    START_SET_MY_SERVICE:"START_SET_MY_SERVICE",
    SUCCESS_SET_MY_SERVICE:"SUCCESS_SET_MY_SERVICE",
    FAILURE_SET_MY_SERVICE:"FAILURE_SET_MY_SERVICE",


    START_SET_MY_WORK:"START_SET_MY_WORK",
    SUCCESS_SET_MY_WORK:"SUCCESS_SET_MY_WORK",
    FAILURE_SET_MY_WORK:"FAILURE_SET_MY_WORK",


    START_SET_OUR_SERVICE:"START_SET_OUR_SERVICE",
    SUCCESS_SET_OUR_SERVICE:"SUCCESS_SET_OUR_SERVICE",
    FAILURE_SET_OUR_SERVICE:"FAILURE_SET_OUR_SERVICE",


    START_SET_OUR_CUSTOMER:"START_SET_OUR_CUSTOMER",
    SUCCESS_SET_OUR_CUSTOMER:"SUCCESS_SET_OUR_CUSTOMER",
    FAILURE_SET_OUR_CUSTOMER:"FAILURE_SET_OUR_CUSTOMER",


    START_SET_OUR_EMPLOYEE:"START_SET_OUR_EMPLOYEE",
    SUCCESS_SET_OUR_EMPLOYEE:"SUCCESS_SET_OUR_EMPLOYEE",
    FAILURE_SET_OUR_EMPLOYEE:"FAILURE_SET_OUR_EMPLOYEE",


    START_SET_NOTIFICATION:"START_SET_NOTIFICATION",
    SUCCESS_SET_NOTIFICATION:"SUCCESS_SET_NOTIFICATION",
    FAILURE_SET_NOTIFICATION:"FAILURE_SET_NOTIFICATION"
}